version: '3'

services:
  pb:
    image: shounnnn/pocketbase:source
    container_name: pb
    ports:
      - 8080:8080
    volumes:
      - ./pb_migrations:/pb/pb_migrations
      - ./pb_hooks:/pb/pb_hooks
      - ./pb_data:/pb/pb_data
