FROM ubuntu as clone
RUN apt-get update
RUN apt-get install -y git
WORKDIR /tmp/
RUN git clone https://github.com/pocketbase/pocketbase


FROM golang:1.22.0-alpine as builder

COPY --from=clone /tmp/pocketbase/examples/base/ /tmp/builder/
WORKDIR /tmp/builder/
RUN CGO_ENABLED=0 go build

FROM alpine:latest

COPY --from=builder /tmp/pocketbase/examples/base/base /pb/pocketbase
COPY ./entrypoint.sh /pb/entrypoint.sh

EXPOSE 8080
# start PocketBase
ENTRYPOINT ["/pb/entrypoint.sh"]
