name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  test-secret:
    runs-on: ubuntu-22.04
    steps:
      - name: print secret
        run: echo "my secret ${{ secrets.DOCKERHUB_USERNAME }}"

  build-dev:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image DEV
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/pocketbase
          tags: dev
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-source:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image SOURCE
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/pocketbase
          tags: source
          registry: docker.io
          dockerfile: Dockerfile.source
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
